Add suffix override option '-e'. Exit if mkdir fails.

diff --git a/qthumb b/qthumb
--- a/qthumb
+++ b/qthumb
@@ -7,12 +7,11 @@
 # You can  pass any arguments along to 'convert' itself, allowing you to use 
 # this as a multi-file wrapper around it.
 
-src=""
+src=
 dst="thumbs"
-
 prefix="thumb_"
 postfix=
-
+suffix=
 convert="convert"
 depth="-maxdepth 1"
 
@@ -24,6 +23,7 @@ usage() {
 	echo "-d <dst>      set destination path   (default: \"$dst\")"
 	echo "-p <prefix>   set target prefix      (default: \"$prefix\")"
 	echo "-P <postfix>  set target postfix     (default: \"$postfix\")"
+	echo "-e <suffix>   set target suffix      (default: source suffix)"
 	echo -e "-r            recursively find files (default: disabled)\n"
 	echo "Only the -s argument is required to run."
 }
@@ -35,6 +35,7 @@ while [ $# -gt 0 ]; do
 		-d) dst="$2";;
 		-p) prefix="$2";;
 		-P) postfix="$2";;
+		-e) suffix="$2";;
 		-r) depth=;;
 		-h) usage
 		    exit 1;;
@@ -52,8 +53,8 @@ if [ $(which "$convert" | wc -l)  = 0 ]; then
 	exit 0
 fi
 
-if [ ! -d $dst ]; then
-	mkdir -pv $dst
+if [ ! -d "$dst" ]; then
+	mkdir -pv "$dst" || exit $?
 fi
 
 find $src $depth -type f | while read old; do
@@ -62,10 +63,15 @@ find $src $depth -type f | while read old; do
 		continue 
 	fi
 
-	type=${old##*.}
+	ext=${old##*.}
 
-	bn=$(basename "$old" ".$type")
-	new="$dst/$prefix$bn$postfix.$type"
+	bn=$(basename "$old" ".$ext")
+
+	if [ "$suffix" != "" ]; then 
+		ext=$suffix
+	fi
+
+	new="$dst/$prefix$bn$postfix.$ext"
 
 	if [ -e "$new" ]; then 
 		echo "Already exists: \"$new\""
@@ -74,5 +80,5 @@ find $src $depth -type f | while read old; do
 
 		
 	echo $convert \"$old\" $@ \"$new\"
-	$convert "$old" $@ "$new" || echo "^ ERROR"
+	$convert "$old" $@ "$new" || echo -e "^ ERROR\n"
 done
