Reconnect even if connected. Fancier output.

diff --git a/wicd-connectto b/wicd-connectto
--- a/wicd-connectto
+++ b/wicd-connectto
@@ -12,6 +12,8 @@
 
 essid=
 use_last=
+persist=
+reconnect=
 last_file="$HOME/.$(basename $0).last_essid"
 dump="/tmp/$(basename $0).tmp"
 
@@ -20,6 +22,8 @@ usage() {
 	echo
 	echo "-e <ID> Use [e]ssid <ESSID>"
 	echo "-l      Use [l]ast ESSID, set in \"$last_file\""
+	echo "-r      Reconnect even if already connected"
+	echo "-K      Keep trying to connect if we fail [not implemented]"
 	echo "-h      Help"
 	echo
 	echo "Example: $(basename $0) -e Diktatorerna"
@@ -34,6 +38,8 @@ while [ $# -gt 0 ]; do
 	case "$1" in
 		-l) use_last=1;;
 		-e) essid=$2;;
+		-K) persist=1;;
+		-r) reconnect=1;;
 		-h) usage
 	esac
 	shift
@@ -46,7 +52,7 @@ which wicd-cli > /dev/null || exit $?
 
 if wicd-cli --status | grep -i "connected to $essid at"; then
 	write_last
-	exit 0
+	[[ $reconnect ]] || exit 0
 fi
 
 echo "Scanning..."
@@ -67,8 +73,9 @@ count_match=${#match_ids[@]}
 echo "$count_all networks, $count_match matching \"$essid\""
 
 if [ $count_match -gt 0 ]; then
-	to_use=${match_ids[0]}
-	echo "Using id $to_use out of pool containing ids: ${match_ids[@]}"
+	let random_index="$RANDOM % $count_match"
+	to_use=${match_ids[$random_index]}
+	echo Selected ID: ${match_ids[@]} | sed "s/ \(${to_use}\)/ [\1]/g"
 	wicd-cli --wireless --connect --network $to_use
 	write_last
 	exit $?
