xe: Improve errorhandling and cleanups

diff --git a/xe b/xe
--- a/xe
+++ b/xe
@@ -1,8 +1,9 @@
 #!/bin/bash
 # Use xe.com to convert currency on the commandline
-
+#
 # Idea stolen from 
 # http://www.commandlinefu.com/commands/view/7866/currency-converter-using-xe.com
+# by gammy
 
 for dep in curl bc sed; do
 	which $dep > /dev/null || exit $?
@@ -16,16 +17,22 @@ fi
 
 amount=$(echo "$1" | bc -l)
 
-# Assumes bash4+
-currency_src="${2^^}"
-currency_dst="${3^^}"
+from="${2::3}" # Truncate to 3 chars
+  to="${3::3}" 
 
-ret=$(curl "http://www.xe.com/wap/2co/convert.cgi?Amount=${amount}&From=${currency_src}&To=${currency_dst}" -A "Mozilla" -s)
-ret=$(echo $ret | sed -n "s/.*>\(.*\) $currency_dst<.*/\1/p")
+args="Amount=${amount}&From=${from}&To=${to}"
+cmd=(curl "http://www.xe.com/wap/2co/convert.cgi?${args}" -A Mozilla -s)
 
-if [ $? -ne 0 ] || [ $ret = "" ] || [ $ret = "ERR" ]; then
-	echo "It appears that script execution failed: cannot convert currency"!
+html=$(${cmd[@]})
+
+code="$?"
+text=$(echo $html | sed -n "s/.*>\(.*\) ${to^^}<.*/\1/p") # Magic
+
+if [ "$code" != "0" -o "$text" == "ERR" -o -z "$text" ]; then
+	dump=$(mktemp)
+	echo -e "'${cmd[@]}' ($code) \"$text\":\n$html" > "$dump"
+	echo "It appears that conversion failed, see \"$dump\" for details" >&2
 	exit 1
 fi
 
-echo "$amount $currency_src = $ret $currency_dst"
+echo "$amount $from = $text $to"
